export const AchievementList = {
  1: {
    name: "10x coal mined",
    id: 0,
    material: "coal",
    unlocked: false,
    amount: 10,
  },
  2: {
    name: "50x coal mined",
    id: 1,
    material: "coal",
    unlocked: false,
    amount: 50,
  },
  3: {
    name: "100x coal mined",
    id: 2,
    material: "coal",
    unlocked: false,
    amount: 100,
  },
  4: {
    name: "1000x coal mined",
    id: 3,
    material: "coal",
    unlocked: false,
    amount: 1000,
  },
  5: {
    name: "10x iron mined",
    id: 4,
    material: "ironore",
    unlocked: false,
    amount: 10,
  },
  6: {
    name: "50x iron mined",
    id: 5,
    material: "ironore",
    unlocked: false,
    amount: 50,
  },
  7: {
    name: "100x iron mined",
    id: 6,
    material: "ironore",
    unlocked: false,
    amount: 100,
  },
  8: {
    name: "1000x iron mined",
    id: 7,
    material: "ironore",
    unlocked: false,
    amount: 1000,
  },
  9: {
    name: "10x gold mined",
    id: 8,
    material: "goldore",
    unlocked: false,
    amount: 10,
  },
  10: {
    name: "50x gold mined",
    id: 9,
    material: "goldore",
    unlocked: false,
    amount: 50,
  },
  11: {
    name: "100x gold mined",
    id: 10,
    material: "goldore",
    unlocked: false,
    amount: 100,
  },
  12: {
    name: "1000x gold mined",
    id: 11,
    material: "goldore",
    unlocked: false,
    amount: 1000,
  },
  13: {
    name: "10x iron ingot melted",
    id: 12,
    material: "ironingot",
    unlocked: false,
    amount: 10,
  },
  14: {
    name: "50x iron ingot melted",
    id: 13,
    material: "ironingot",
    unlocked: false,
    amount: 50,
  },
  15: {
    name: "100x iron ingot melted",
    id: 14,
    material: "ironingot",
    unlocked: false,
    amount: 100,
  },
  16: {
    name: "1000x iron ingot melted",
    id: 15,
    material: "ironingot",
    unlocked: false,
    amount: 1000,
  },
  17: {
    name: "10x gold ingot melted",
    id: 16,
    material: "goldingot",
    unlocked: false,
    amount: 10,
  },
  18: {
    name: "50x gold ingot melted",
    id: 17,
    material: "goldingot",
    unlocked: false,
    amount: 50,
  },
  19: {
    name: "100x gold ingot melted",
    id: 18,
    material: "goldingot",
    unlocked: false,
    amount: 100,
  },
  20: {
    name: "1000x gold ingot melted",
    id: 19,
    material: "goldingot",
    unlocked: false,
    amount: 1000,
  },
};
