export const InventoryLS = {
  coal: {
    amount: 0,
    id: "0",
    name: "coal",
    worth: 1,
    identifier: "coal",
    overallAmount: 0,
  },
  ironore: {
    amount: 0,
    id: "1",
    name: "iron ore",
    worth: 3,
    identifier: "ironore",
    overallAmount: 0,
  },
  goldore: {
    amount: 0,
    id: "2",
    name: "gold ore",
    worth: 5,
    identifier: "goldore",
    overallAmount: 0,
  },
  ironingot: {
    amount: 0,
    id: "3",
    name: "iron ingot",
    worth: 10,
    identifier: "ironingot",
    overallAmount: 0,
  },
  goldingot: {
    amount: 0,
    id: "4",
    name: "gold ingot",
    worth: 15,
    identifier: "goldingot",
    overallAmount: 0,
  },
  woodstick: {
    amount: 0,
    id: "5",
    name: "wood sticks",
    worth: 1,
    price: 2,
    identifier: "woodstick",
  },
  gear: {
    amount: 0,
    id: "6",
    name: "gear",
    worth: 7,
    identifier: "gear",
  },
  goldarmor: {
    amount: 0,
    id: "7",
    name: "gold armor",
    worth: 70,
    identifier: "goldarmor",
  },
  dwarfi: { amount: 0, id: "99", name: "dwarfi" },
};
